// =============================================================================
//  Family Design Tokens — Phase 32.75 Tier 3
//
//  Each composition family supplies a self-contained token set every smart
//  component inherits. Adding a new family means filling out this table only;
//  the 20 smart-component builders pick up the new look automatically.
// =============================================================================

import type { SmartFamilyId } from './smart-types';

export interface FamilyTokens {
  /** Primary brand colour. Used for headlines, key metrics, button fills. */
  accent: string;
  /** Secondary accent — used for secondary chart series, badges. */
  accent2: string;
  /** Default text colour on the family's canvas. */
  text: string;
  /** Muted text (captions, axis labels, footers). */
  muted: string;
  /** Slide-level background (solid or gradient). */
  bg: string;
  /** Card / surface fill. */
  surface: string;
  /** Border colour for cards and dividers. */
  border: string;
  /** Subtle divider (rules inside cards). */
  divider: string;
  /** Positive / negative semantic colours. */
  positive: string;
  negative: string;
  /** Card radius in px (0 for sharp, ≥10 for soft). */
  radius: number;
  /** Strokes — set to 0 for borderless cards. */
  strokeWidth: number;
  /** Card elevation (CSS box-shadow). */
  shadow: string;
  /** Heading + body fonts. */
  fontHeading: string;
  fontBody: string;
  /** Default weight bumps — e.g. luxury wants lighter weight. */
  fontWeightHeading: number;
  fontWeightBody: number;
  /** Spacing scale modifier — 1 = normal, >1 = looser. */
  spacing: number;
  /** Numbers feel — 'tabular' or 'proportional'. Used as letter-spacing. */
  numberLetterSpacing: number;
  /** Casing for labels — 'uppercase' for restrained corporate, etc. */
  labelTransform: 'uppercase' | 'none';
  /** Mood descriptor (also a tag for the registry). */
  mood: string;
  /** Whether the family is on a dark canvas — flips a few choices. */
  isDark: boolean;
}

const FAMILIES: Record<SmartFamilyId, FamilyTokens> = {
  'crimson-dark': {
    accent: '#ef4444',
    accent2: '#fb923c',
    text: '#fafafa',
    muted: '#a1a1aa',
    bg: '#18181b',
    surface: '#27272a',
    border: 'rgba(239,68,68,0.35)',
    divider: 'rgba(255,255,255,0.06)',
    positive: '#22c55e',
    negative: '#f87171',
    radius: 4,
    strokeWidth: 1,
    shadow: '0 8px 24px rgba(0,0,0,0.45)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 800,
    fontWeightBody: 500,
    spacing: 1.0,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'dramatic',
    isDark: true,
  },
  'light-blue-business': {
    accent: '#2563eb',
    accent2: '#0ea5e9',
    text: '#0f172a',
    muted: '#64748b',
    bg: '#f8fafc',
    surface: '#ffffff',
    border: '#e2e8f0',
    divider: '#f1f5f9',
    positive: '#16a34a',
    negative: '#dc2626',
    radius: 8,
    strokeWidth: 1,
    shadow: '0 1px 3px rgba(15,23,42,0.06)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.0,
    numberLetterSpacing: 0,
    labelTransform: 'none',
    mood: 'corporate',
    isDark: false,
  },
  'luxury-dark': {
    accent: '#d4af37',
    accent2: '#facc15',
    text: '#f5f5f4',
    muted: '#a8a29e',
    bg: '#0c0a09',
    surface: '#1c1917',
    border: 'rgba(212,175,55,0.3)',
    divider: 'rgba(212,175,55,0.12)',
    positive: '#a3e635',
    negative: '#fb7185',
    radius: 2,
    strokeWidth: 0.5,
    shadow: '0 16px 40px rgba(0,0,0,0.6)',
    fontHeading: '"Playfair Display", Georgia, serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 300,
    spacing: 1.3,
    numberLetterSpacing: -1.5,
    labelTransform: 'uppercase',
    mood: 'premium',
    isDark: true,
  },
  'startup-gradient': {
    accent: '#38bdf8',
    accent2: '#818cf8',
    text: '#ffffff',
    muted: 'rgba(255,255,255,0.72)',
    bg: 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 55%, #1e40af 100%)',
    surface: 'rgba(255,255,255,0.1)',
    border: 'rgba(56,189,248,0.3)',
    divider: 'rgba(255,255,255,0.1)',
    positive: '#86efac',
    negative: '#fda4af',
    radius: 12,
    strokeWidth: 1,
    shadow: '0 8px 28px rgba(30,58,138,0.55)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 800,
    fontWeightBody: 500,
    spacing: 1.05,
    numberLetterSpacing: -1,
    labelTransform: 'none',
    mood: 'growth',
    isDark: true,
  },
  'corporate-monochrome': {
    accent: '#475569',
    accent2: '#94a3b8',
    text: '#1e293b',
    muted: '#64748b',
    bg: '#ffffff',
    surface: '#f8fafc',
    border: '#cbd5e1',
    divider: '#e2e8f0',
    positive: '#16a34a',
    negative: '#dc2626',
    radius: 6,
    strokeWidth: 1,
    shadow: 'none',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 600,
    fontWeightBody: 400,
    spacing: 1.0,
    numberLetterSpacing: 0,
    labelTransform: 'uppercase',
    mood: 'neutral',
    isDark: false,
  },
  'editorial-report': {
    accent: '#0f172a',
    accent2: '#7c2d12',
    text: '#0f172a',
    muted: '#475569',
    bg: '#fefdf8',
    surface: '#ffffff',
    border: '#d6d3d1',
    divider: '#e7e5e4',
    positive: '#15803d',
    negative: '#b91c1c',
    radius: 2,
    strokeWidth: 1.5,
    shadow: 'none',
    fontHeading: '"Playfair Display", Georgia, serif',
    fontBody: 'Lora, Georgia, serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 0.95,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'editorial',
    isDark: false,
  },
  'investor-minimal': {
    accent: '#ea580c',
    accent2: '#f59e0b',
    text: '#1c1917',
    muted: '#78716c',
    bg: '#fafaf9',
    surface: '#ffffff',
    border: '#e7e5e4',
    divider: '#f5f5f4',
    positive: '#16a34a',
    negative: '#dc2626',
    radius: 4,
    strokeWidth: 0.75,
    shadow: 'none',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.25,
    numberLetterSpacing: -1,
    labelTransform: 'uppercase',
    mood: 'minimal',
    isDark: false,
  },
  'soft-geometric-blue': {
    accent: '#60a5fa',
    accent2: '#38bdf8',
    text: '#1e293b',
    muted: '#64748b',
    bg: '#eff6ff',
    surface: '#ffffff',
    border: '#bfdbfe',
    divider: '#dbeafe',
    positive: '#22c55e',
    negative: '#ef4444',
    radius: 12,
    strokeWidth: 1,
    shadow: '0 4px 12px rgba(96,165,250,0.15)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.0,
    numberLetterSpacing: -0.25,
    labelTransform: 'none',
    mood: 'geometric',
    isDark: false,
  },

  // ── Phase 4: 12 new premium families ─────────────────────────────────────

  'ocean-deep': {
    accent: '#0ea5e9',
    accent2: '#38bdf8',
    text: '#e2e8f0',
    muted: '#94a3b8',
    bg: '#0c1524',
    surface: '#162236',
    border: 'rgba(14,165,233,0.22)',
    divider: 'rgba(255,255,255,0.06)',
    positive: '#34d399',
    negative: '#f87171',
    radius: 8,
    strokeWidth: 1,
    shadow: '0 8px 24px rgba(0,0,0,0.45)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.05,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'financial',
    isDark: true,
  },

  'forest-executive': {
    accent: '#22c55e',
    accent2: '#86efac',
    text: '#f0fdf4',
    muted: '#86efac',
    bg: '#071510',
    surface: '#0f2118',
    border: 'rgba(34,197,94,0.25)',
    divider: 'rgba(34,197,94,0.08)',
    positive: '#4ade80',
    negative: '#fb7185',
    radius: 4,
    strokeWidth: 1,
    shadow: '0 12px 32px rgba(0,0,0,0.5)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.1,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'executive',
    isDark: true,
  },

  'ember-orange': {
    accent: '#f97316',
    accent2: '#fbbf24',
    text: '#ffffff',
    muted: 'rgba(255,255,255,0.72)',
    bg: 'linear-gradient(135deg, #f97316 0%, #f59e0b 100%)',
    surface: 'rgba(255,255,255,0.15)',
    border: 'rgba(255,255,255,0.28)',
    divider: 'rgba(255,255,255,0.12)',
    positive: '#bbf7d0',
    negative: '#fca5a5',
    radius: 14,
    strokeWidth: 1,
    shadow: '0 8px 28px rgba(249,115,22,0.42)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 800,
    fontWeightBody: 500,
    spacing: 1.05,
    numberLetterSpacing: -0.8,
    labelTransform: 'none',
    mood: 'energetic',
    isDark: true,
  },

  'arctic-white': {
    accent: '#334155',
    accent2: '#475569',
    text: '#0f172a',
    muted: '#64748b',
    bg: '#ffffff',
    surface: '#f8fafc',
    border: '#e2e8f0',
    divider: '#f1f5f9',
    positive: '#166534',
    negative: '#991b1b',
    radius: 0,
    strokeWidth: 1.5,
    shadow: 'none',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 600,
    fontWeightBody: 400,
    spacing: 1.35,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'ultra-minimal',
    isDark: false,
  },

  'slate-pro': {
    accent: '#818cf8',
    accent2: '#6ee7b7',
    text: '#f8fafc',
    muted: '#94a3b8',
    bg: '#0b0f1a',
    surface: '#141d2e',
    border: 'rgba(129,140,248,0.3)',
    divider: 'rgba(255,255,255,0.05)',
    positive: '#6ee7b7',
    negative: '#f87171',
    radius: 3,
    strokeWidth: 1.5,
    shadow: '0 4px 20px rgba(129,140,248,0.2)',
    fontHeading: '"DM Sans", Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 600,
    fontWeightBody: 400,
    spacing: 1.15,
    numberLetterSpacing: -1.2,
    labelTransform: 'uppercase',
    mood: 'saas',
    isDark: true,
  },

  'emerald-fintech': {
    accent: '#059669',
    accent2: '#34d399',
    text: '#0a2218',
    muted: '#3d7a5c',
    bg: '#f0fdf4',
    surface: '#ffffff',
    border: '#bbf7d0',
    divider: '#d1fae5',
    positive: '#15803d',
    negative: '#dc2626',
    radius: 8,
    strokeWidth: 1,
    shadow: '0 2px 8px rgba(5,150,105,0.09)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.0,
    numberLetterSpacing: -0.25,
    labelTransform: 'none',
    mood: 'growth',
    isDark: false,
  },

  'midnight-tech': {
    accent: '#06b6d4',
    accent2: '#22d3ee',
    text: '#e2e8f0',
    muted: '#64748b',
    bg: '#03060c',
    surface: '#0d1117',
    border: 'rgba(6,182,212,0.22)',
    divider: 'rgba(6,182,212,0.07)',
    positive: '#22d3ee',
    negative: '#f87171',
    radius: 6,
    strokeWidth: 1,
    shadow: '0 8px 24px rgba(6,182,212,0.18)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.05,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'tech',
    isDark: true,
  },

  'rose-modern': {
    accent: '#f43f5e',
    accent2: '#fb7185',
    text: '#1f0a10',
    muted: '#9f4460',
    bg: '#fff1f3',
    surface: '#ffffff',
    border: '#fecdd3',
    divider: '#ffe4e6',
    positive: '#166534',
    negative: '#be123c',
    radius: 12,
    strokeWidth: 1,
    shadow: '0 4px 12px rgba(244,63,94,0.1)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.05,
    numberLetterSpacing: -0.25,
    labelTransform: 'none',
    mood: 'warm',
    isDark: false,
  },

  'cobalt-impact': {
    accent: '#60a5fa',
    accent2: '#93c5fd',
    text: '#ffffff',
    muted: 'rgba(255,255,255,0.68)',
    bg: 'linear-gradient(150deg, #1e3a8a 0%, #1d4ed8 100%)',
    surface: 'rgba(255,255,255,0.1)',
    border: 'rgba(255,255,255,0.2)',
    divider: 'rgba(255,255,255,0.08)',
    positive: '#86efac',
    negative: '#fca5a5',
    radius: 10,
    strokeWidth: 1,
    shadow: '0 8px 28px rgba(29,78,216,0.5)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.0,
    numberLetterSpacing: -0.5,
    labelTransform: 'none',
    mood: 'enterprise',
    isDark: true,
  },

  'warm-sand': {
    accent: '#92400e',
    accent2: '#b45309',
    text: '#1c0a00',
    muted: '#78350f',
    bg: '#fffbf3',
    surface: '#ffffff',
    border: '#fed7aa',
    divider: '#fef3c7',
    positive: '#166534',
    negative: '#b91c1c',
    radius: 8,
    strokeWidth: 1,
    shadow: 'none',
    fontHeading: '"Playfair Display", Georgia, serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.2,
    numberLetterSpacing: -0.5,
    labelTransform: 'uppercase',
    mood: 'lifestyle',
    isDark: false,
  },

  'violet-creative': {
    accent: '#a78bfa',
    accent2: '#c4b5fd',
    text: '#f3f0ff',
    muted: '#c4b5fd',
    bg: '#16102e',
    surface: '#1e1545',
    border: 'rgba(167,139,250,0.35)',
    divider: 'rgba(167,139,250,0.1)',
    positive: '#a3e635',
    negative: '#fb7185',
    radius: 12,
    strokeWidth: 1,
    shadow: '0 8px 24px rgba(124,58,237,0.4)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 800,
    fontWeightBody: 400,
    spacing: 1.0,
    numberLetterSpacing: -0.5,
    labelTransform: 'none',
    mood: 'creative',
    isDark: true,
  },

  'teal-health': {
    accent: '#0d9488',
    accent2: '#14b8a6',
    text: '#0d2b28',
    muted: '#2d6b68',
    bg: '#f0fdfc',
    surface: '#ffffff',
    border: '#99f6e4',
    divider: '#ccfbf1',
    positive: '#16a34a',
    negative: '#dc2626',
    radius: 10,
    strokeWidth: 1,
    shadow: '0 2px 8px rgba(13,148,136,0.09)',
    fontHeading: 'Inter, system-ui, sans-serif',
    fontBody: 'Inter, system-ui, sans-serif',
    fontWeightHeading: 700,
    fontWeightBody: 400,
    spacing: 1.05,
    numberLetterSpacing: -0.25,
    labelTransform: 'none',
    mood: 'health',
    isDark: false,
  },
};

export function getFamilyTokens(family: SmartFamilyId): FamilyTokens {
  return FAMILIES[family];
}

/** Internal — used by the validator. */
export const ALL_FAMILY_TOKENS: Readonly<Record<SmartFamilyId, FamilyTokens>> = FAMILIES;
